default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: dev
  password: qwerty

development:
  <<: *default
  database: pusher-chat_development

test:
  <<: *default
  database: pusher-chat_test

production:
  <<: *default
  database: pusher-chat_production
  username: pusher-chat
  password: <%= ENV['PUSHER-CHAT_DATABASE_PASSWORD'] %>
